<a href="https://colab.research.google.com/github/pragya-sirse/Foun.-of-Data-science/blob/main/Numpy_lab_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.numpy program to get numpy version
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
#2.test wheather none of the element of a given array are zero
x=np.array([1,2,3,0])
x

array([1, 2, 3, 0])

In [ ]:
print("checking whether none of the elemnet of a given array are zero")
x=np.all(x)
x

checking whether none of the elemnet of a given array are zero


False

In [ ]:
#3.numpy program to create an element wise comparison
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a>b)
print(a>=b)
print(a<=b)

[False False False False]
[ True  True  True  True]
[ True  True  True  True]


In [ ]:
#4.determine the size of array
x=np.array([1,7,13,105])
x.nbytes

32

In [ ]:
#5.numpy program to create array of int from 30 to 70
x=np.arange(30,70)
x

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [ ]:
#6.numpy program to create array all even int from 30 to 70
x=np.arange(30,70,2)
x

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [ ]:
#7.create 3x3 indentity matrix
a=np.identity(3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#8. 3x4 array and iter over it
a=np.arange(10,22).reshape((3,4))
for i in np.nditer(a):
  print(i)

10
11
12
13
14
15
16
17
18
19
20
21


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Check if none of the elements are zero
if np.all(arr != 0):
    print("None of the elements are zero.")
else:
    print("Some of the elements are zero.")

None of the elements are zero.


In [ ]:
arr = np.arange(30, 71)

# Filter out even integers
even_arr = arr[arr % 2 == 0]

# Print array
print( even_arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
identity_matrix = np.eye(3)

# Print matrix

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
