<a href="https://colab.research.google.com/github/pragya-sirse/Foun.-of-Data-science/blob/main/Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[1,2],[2,3],[6,7]])
print(b)


[[1 2]
 [2 3]
 [6 7]]


In [6]:
c=np.array([[[1,2,3],[3,4,6],[8,9,8],[9,10,4]]])
print(c)

[[[ 1  2  3]
  [ 3  4  6]
  [ 8  9  8]
  [ 9 10  4]]]


In [7]:
d=np.array([1,2,3], dtype=float)
print(d)


[1. 2. 3.]


In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.random.random((3,4))

array([[0.29267891, 0.50968381, 0.86434638, 0.43806222],
       [0.62459682, 0.83570996, 0.71576986, 0.90753594],
       [0.84283968, 0.31896897, 0.53374154, 0.65658213]])

In [14]:
np.linspace(7,8,10)

array([7.        , 7.11111111, 7.22222222, 7.33333333, 7.44444444,
       7.55555556, 7.66666667, 7.77777778, 7.88888889, 8.        ])

In [15]:
np.identity(3) # gives the identity element

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes


In [16]:
a1=np.arange(10) # giving the element in range of 10
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a2=np.arange(12, dtype=float).reshape(3,4) # giving array of 12 element in 1d
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
a3=np.arange(16).reshape(2,2,2,2) # giving array of 16 element in 4d
a3

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [19]:
a3.ndim ## it shows the dimension of array

4

In [20]:
a1.shape # indicates the dimension of array
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a3.size ## gives the no. of items

16

In [22]:
a2.size # gives the no. of element

12

In [23]:
a1.itemsize # gives the length of array element in bytes

8

In [24]:
## gives the data type
a1.dtype
a2.dtype
a3.dtype


dtype('int64')

**changing data type**


In [25]:
a3.dtype # we can check the dtype of element

dtype('int64')

In [26]:
a3.astype(np.int32) ## astype to convert the dtype ,remeber it as type of data

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]], dtype=int32)

**Array Operations**

In [31]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
# scalar operation
#arithmatic
a1**2 # it is giving o/p by squaring of  2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
a1=np.arange(12).reshape(3,4)
a1^2

array([[ 2,  3,  0,  1],
       [ 6,  7,  4,  5],
       [10, 11,  8,  9]])

In [ ]:
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
## vector operation
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

**Array Functions**

In [ ]:
a1=np.random.random((3,3))
a2=np.round(a1*100)
a2

array([[48., 66., 47.],
       [50., 73., 68.],
       [ 2., 46., 34.]])

In [ ]:
np.prod(a1)

0.00012187146748962823

In [ ]:
np.sum(a1)

4.3580815543433715

In [ ]:
np.max(a1,axis=1)

array([0.66018969, 0.73307703, 0.46339616])

In [ ]:
np.max(a1,axis=0)

array([0.50482587, 0.73307703, 0.68278949])

In [ ]:
np.min(a1)

0.020475165401281803

In [ ]:
np.mean(a1)

0.48423128381593017

In [ ]:
np.median(a1)

0.48211787230333325

In [ ]:
np.std(a1)

0.20282062981559057

In [ ]:
np.var(a1)

0.041136207878792824

In [ ]:
np.sin(a1)

array([[0.46365668, 0.61326669, 0.457297  ],
       [0.48365504, 0.6691594 , 0.63095961],
       [0.02047373, 0.44698868, 0.32995593]])

In [ ]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
a3
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
np.exp(a1)

array([[1.61950067, 1.93515938, 1.60793925],
       [1.65669701, 2.08147552, 1.97939154],
       [1.02068622, 1.5894629 , 1.39969855]])

In [ ]:
np.round(np.random.random((2,3))*100)

array([[58., 80., 70.],
       [94., 26., 81.]])

In [ ]:
np.floor(np.random.random((2,3))*100)

array([[61., 13., 91.],
       [62., 65., 70.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[82., 94., 97.],
       [62., 32., 16.]])

***Indexing and Slicing***

In [ ]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

9

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a2[1,2]


18

In [33]:
a2[2,3]


23

In [34]:

a2[1,0]

16

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[0,1,1]

3

In [ ]:
a3[0,0,0]

0

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [35]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
a2[0,:]

array([0., 1., 2., 3.])

In [36]:
a2[:,2]

array([14, 18, 22])

In [ ]:
a2[0,:3]

array([0, 1, 2])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**Iterating**

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [37]:
for i in np.nditer(a3):
  print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


**Reshaping**

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**Stacking**

In [ ]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]